name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Go and Jest tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Go modules
        id: cache-go
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go modules
        shell: bash
        if: ${{ steps.cache-go.outputs.cache-hit != 'true' }}
        run: |
          cd lt-api
          go mod download

      - name: Run Go tests
        run: |
          cd lt-api
          go test ./...

      - name: Install dependencies
        run: |
          cd lt-front
          npm i

      - name: Run Jest tests
        run: |
          cd lt-front
          npm run test
  build-and-push:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "auth gcp"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - id: "setup"
        name: "Setup Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Authorized Docker push"
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: set TAG
        run: |
          echo "TAG=$(echo $GITHUB_REF | awk -F/ '{print $NF}')" >> $GITHUB_ENV

      - name: build and push
        run: |-
          docker build -t us-west1-docker.pkg.dev/lightning-neko-talk/lt-api/api-image:${{ env.TAG }} ./lt-api
          docker push us-west1-docker.pkg.dev/lightning-neko-talk/lt-api/api-image:${{ env.TAG }}
