name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Go and Jest tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Go modules
        id: cache-go
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go modules
        shell: bash
        if: ${{ steps.cache-go.outputs.cache-hit != 'true' }}
        run: |
          cd lt-api
          go mod download

      - name: Run Go tests
        run: |
          cd lt-api
          go test ./...

      - name: Install dependencies
        run: |
          cd lt-front
          npm i

      - name: Run Jest tests
        run: |
          cd lt-front
          npm run test
  build-and-push:
    name: Build and Push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCLOUD__AUTH }}
          project_id: lightning-neko-talk

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: set TAG
        run: |
          echo "TAG=$(echo $GITHUB_REF | awk -F/ '{print $NF}')" >> $GITHUB_ENV

      - name: Build
        run: docker build -t us-west1-docker.pkg.dev/lightning-neko-talk/lt-api/api-image:${{ env.TAG }} ./lt-api

      - name: Push
        run: |
          docker push us-west1-docker.pkg.dev/lightning-neko-talk/lt-api/api-image:${{ env.TAG }}
