name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Go and Jest tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Replace with your required Node.js version

      - name: Cache Go modules
        id: cache-go
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go modules
        shell: bash
        if: ${{ steps.cache-go.outputs.cache-hit != 'true' }}
        run: |
          cd lt-api
          go mod download

      - name: Run Go tests
        run: |
          cd lt-api
          go test ./...

      - name: Install dependencies
        run: |
          cd lt-front
          npm i

      - name: Run Jest tests
        run: |
          cd lt-front
          npm run test
